# Generated by Django 4.2.1 on 2023-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discription', models.CharField(max_length=10000)),
                ('adress', models.CharField(max_length=2000)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
    ]
