# Generated by Django 4.2.1 on 2023-05-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_adress_ads_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='name',
        ),
    ]
